/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OsacNetworkingCredentials } from './OsacNetworkingCredentials.js';
import {
    OsacNetworkingCredentialsFromJSON,
    OsacNetworkingCredentialsToJSON,
} from './OsacNetworkingCredentials.js';

/**
 *
 * @export
 * @interface OsacNetworkingNetris
 */
export interface OsacNetworkingNetris {
    /**
     * Netris controller API URL (HTTPS)
     * @type {string}
     * @memberof OsacNetworkingNetris
     */
    controllerUrl?: string;
    /**
     * Netris API credentials
     * @type {OsacNetworkingCredentials}
     * @memberof OsacNetworkingNetris
     */
    credentials?: OsacNetworkingCredentials;
    /**
     * Management VPC ID in Netris
     * @type {string}
     * @memberof OsacNetworkingNetris
     */
    mgmtVpcId?: string;
    /**
     * Management VPC name in Netris
     * @type {string}
     * @memberof OsacNetworkingNetris
     */
    mgmtVpcName?: string;
    /**
     * JSON mapping resource classes to Netris server cluster templates
     * @type {string}
     * @memberof OsacNetworkingNetris
     */
    resourceClassMap?: string;
    /**
     * Netris site ID
     * @type {string}
     * @memberof OsacNetworkingNetris
     */
    siteId?: string;
    /**
     * Netris tenant ID
     * @type {string}
     * @memberof OsacNetworkingNetris
     */
    tenantId?: string;
    /**
     * Netris tenant name
     * @type {string}
     * @memberof OsacNetworkingNetris
     */
    tenantName?: string;
}

/**
 * Check if a given object implements the OsacNetworkingNetris interface.
 */
export function instanceOfOsacNetworkingNetris(value: object): value is OsacNetworkingNetris {
    return true;
}

export function OsacNetworkingNetrisFromJSON(json: any): OsacNetworkingNetris {
    return OsacNetworkingNetrisFromJSONTyped(json, false);
}

export function OsacNetworkingNetrisFromJSONTyped(json: any, _ignoreDiscriminator: boolean): OsacNetworkingNetris {
    if (json == null) {
        return json;
    }
    return {
        'controllerUrl': json['controllerUrl'] == null ? undefined : json['controllerUrl'],
        'credentials': json['credentials'] == null ? undefined : OsacNetworkingCredentialsFromJSON(json['credentials']),
        'mgmtVpcId': json['mgmtVpcId'] == null ? undefined : json['mgmtVpcId'],
        'mgmtVpcName': json['mgmtVpcName'] == null ? undefined : json['mgmtVpcName'],
        'resourceClassMap': json['resourceClassMap'] == null ? undefined : json['resourceClassMap'],
        'siteId': json['siteId'] == null ? undefined : json['siteId'],
        'tenantId': json['tenantId'] == null ? undefined : json['tenantId'],
        'tenantName': json['tenantName'] == null ? undefined : json['tenantName'],
    };
}

export function OsacNetworkingNetrisToJSON(json: any): OsacNetworkingNetris {
    return OsacNetworkingNetrisToJSONTyped(json, false);
}

export function OsacNetworkingNetrisToJSONTyped(value?: OsacNetworkingNetris | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'controllerUrl': value['controllerUrl'],
        'credentials': OsacNetworkingCredentialsToJSON(value['credentials']),
        'mgmtVpcId': value['mgmtVpcId'],
        'mgmtVpcName': value['mgmtVpcName'],
        'resourceClassMap': value['resourceClassMap'],
        'siteId': value['siteId'],
        'tenantId': value['tenantId'],
        'tenantName': value['tenantName'],
    };
}
