/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OsacNetworkingNetris } from './OsacNetworkingNetris.js';
import {
    OsacNetworkingNetrisFromJSON,
    OsacNetworkingNetrisToJSON,
} from './OsacNetworkingNetris.js';

/**
 *
 * @export
 * @interface OsacNetworkingConfig
 */
export interface OsacNetworkingConfig {
    /**
     * Fabric manager profile: empty string, netris, or reserved cudn_net/vlan
     * @type {string}
     * @memberof OsacNetworkingConfig
     */
    fabricManager: string;
    /**
     * Kubernetes manager profile: empty string or k8s_only
     * @type {string}
     * @memberof OsacNetworkingConfig
     */
    k8sManager: string;
    /**
     * Netris fabric manager configuration
     * @type {OsacNetworkingNetris}
     * @memberof OsacNetworkingConfig
     */
    netris?: OsacNetworkingNetris;
}

/**
 * Check if a given object implements the OsacNetworkingConfig interface.
 */
export function instanceOfOsacNetworkingConfig(value: object): value is OsacNetworkingConfig {
    if (!('fabricManager' in value) || value['fabricManager'] === undefined) return false;
    if (!('k8sManager' in value) || value['k8sManager'] === undefined) return false;
    return true;
}

export function OsacNetworkingConfigFromJSON(json: any): OsacNetworkingConfig {
    return OsacNetworkingConfigFromJSONTyped(json, false);
}

export function OsacNetworkingConfigFromJSONTyped(json: any, _ignoreDiscriminator: boolean): OsacNetworkingConfig {
    if (json == null) {
        return json;
    }
    return {
        'fabricManager': json['fabricManager'],
        'k8sManager': json['k8sManager'],
        'netris': json['netris'] == null ? undefined : OsacNetworkingNetrisFromJSON(json['netris']),
    };
}

export function OsacNetworkingConfigToJSON(json: any): OsacNetworkingConfig {
    return OsacNetworkingConfigToJSONTyped(json, false);
}

export function OsacNetworkingConfigToJSONTyped(value?: OsacNetworkingConfig | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'fabricManager': value['fabricManager'],
        'k8sManager': value['k8sManager'],
        'netris': OsacNetworkingNetrisToJSON(value['netris']),
    };
}
