/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OsacNetworkingCredentials
 */
export interface OsacNetworkingCredentials {
    /**
     * Use externally managed netris-credentials Secret instead of inline password
     * @type {boolean}
     * @memberof OsacNetworkingCredentials
     */
    externalSecret?: boolean;
    /**
     * Netris API password (inline)
     * @type {string}
     * @memberof OsacNetworkingCredentials
     */
    password?: string;
    /**
     * Netris API username
     * @type {string}
     * @memberof OsacNetworkingCredentials
     */
    username?: string;
}

/**
 * Check if a given object implements the OsacNetworkingCredentials interface.
 */
export function instanceOfOsacNetworkingCredentials(value: object): value is OsacNetworkingCredentials {
    return true;
}

export function OsacNetworkingCredentialsFromJSON(json: any): OsacNetworkingCredentials {
    return OsacNetworkingCredentialsFromJSONTyped(json, false);
}

export function OsacNetworkingCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OsacNetworkingCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'externalSecret': json['externalSecret'] == null ? undefined : json['externalSecret'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function OsacNetworkingCredentialsToJSON(json: any): OsacNetworkingCredentials {
    return OsacNetworkingCredentialsToJSONTyped(json, false);
}

export function OsacNetworkingCredentialsToJSONTyped(value?: OsacNetworkingCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalSecret': value['externalSecret'],
        'password': value['password'],
        'username': value['username'],
    };
}

