/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and get a bearer token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change admin password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load existing configuration
         * @description Reads config/global.yaml, config/certificates.yaml, and config/cloud_infra.yaml from the Enclave directory and returns the merged configuration.
         */
        get: operations["get-config"];
        /**
         * Write configuration to disk
         * @description Accepts wizard state, serializes to YAML, and writes to the Enclave config directory.
         */
        put: operations["write-config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load TLS certificates */
        get: operations["get-config-certificates"];
        /** Update TLS certificates */
        put: operations["write-config-certificates"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Management cluster install configuration */
        get: operations["get-config-cluster"];
        /** Update Management cluster install configuration */
        put: operations["write-config-cluster"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Discovery hosts (cloud infrastructure) */
        get: operations["get-config-hosts"];
        /** Update Discovery hosts (cloud infrastructure) */
        put: operations["write-config-hosts"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/lz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Landing zone configuration */
        get: operations["get-config-lz"];
        /** Update Landing zone configuration */
        put: operations["write-config-lz"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Host network configuration */
        get: operations["get-config-network"];
        /** Update Host network configuration */
        put: operations["write-config-network"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Enabled plugins configuration */
        get: operations["get-config-plugins"];
        /** Update Enabled plugins configuration */
        put: operations["write-config-plugins"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview rendered YAML
         * @description Returns the rendered YAML content for each config file without writing to disk.
         */
        post: operations["preview-config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/quay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Quay registry configuration */
        get: operations["get-config-quay"];
        /** Update Quay registry configuration */
        put: operations["write-config-quay"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Block storage configuration */
        get: operations["get-config-storage"];
        /** Update Block storage configuration */
        put: operations["write-config-storage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate configuration
         * @description Validates the candidate configuration against Enclave JSON schemas and returns structured errors.
         */
        post: operations["validate-config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get default configuration values
         * @description Returns default values read from defaults/deployment.yaml and plugin definitions.
         */
        get: operations["get-defaults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available plugins
         * @description Returns all known plugins and their types.
         */
        get: operations["list-plugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate plugin combination
         * @description Checks whether the given set of plugins forms a valid deployment combination.
         */
        post: operations["validate-plugin-combination"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all task runs
         * @description Returns all known task runs, most recent first.
         */
        get: operations["list-tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start full deployment
         * @description Runs the main.yaml playbook (all 7 phases).
         */
        post: operations["start-deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/deploy/{phase}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a specific deployment phase
         * @description Runs a single deployment phase (1-7).
         */
        post: operations["start-deploy-phase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/plugins/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy a plugin
         * @description Runs the deploy-plugin.yaml playbook for the named plugin.
         */
        post: operations["start-deploy-plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run operational validation (validations.sh)
         * @description Runs the enclave operational validation script that checks DNS, Redfish, certificates, and registry connectivity.
         */
        post: operations["start-validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get task run details
         * @description Returns status and metadata for a specific run.
         */
        get: operations["get-task"];
        put?: never;
        post?: never;
        /**
         * Delete a task run
         * @description Removes the ansible-runner directory for the given run. Returns 409 if the task is still running.
         */
        delete: operations["delete-task"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get task job events
         * @description Returns ansible-runner job events as a JSON array.
         */
        get: operations["get-task-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get task output logs
         * @description Returns ansible-runner stdout as text/plain. Use the offset query parameter for incremental reads.
         */
        get: operations["get-task-logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CertificatesConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CertificatesConfig.json
             */
            readonly $schema?: string;
            /** @description PEM-encoded TLS cert for Ironic vmedia HTTPS */
            ironicHTTPSCertificate?: string;
            /** @description PEM-encoded private key for Ironic HTTPS cert */
            ironicHTTPSKey?: string;
            /** @description PEM-encoded full cert chain for API server */
            sslAPICertificateFullChain?: string;
            /** @description PEM-encoded private key for API server cert */
            sslAPICertificateKey?: string;
            /** @description PEM-encoded root CA certificate */
            sslCACertificate?: string;
            /** @description PEM-encoded full cert chain for ingress wildcard */
            sslIngressCertificateFullChain?: string;
            /** @description PEM-encoded private key for ingress cert */
            sslIngressCertificateKey?: string;
        };
        ChangePasswordInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChangePasswordInputBody.json
             */
            readonly $schema?: string;
            /** @description Current password */
            currentPassword: string;
            /** @description New password (min 8 characters) */
            newPassword: string;
        };
        ChangePasswordOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChangePasswordOutputBody.json
             */
            readonly $schema?: string;
            /** @description New bearer token (previous tokens are invalidated) */
            token: string;
        };
        CloudInfraConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CloudInfraConfig.json
             */
            readonly $schema?: string;
            /** @description Worker nodes for hardware discovery */
            discovery_hosts: components["schemas"]["HostEntry"][] | null;
        };
        ClusterConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ClusterConfig.json
             */
            readonly $schema?: string;
            /** @description Control plane nodes (exactly 3) */
            agent_hosts: components["schemas"]["HostEntry"][] | null;
            /** @description Virtual IP for Kubernetes API server */
            apiVIP: string;
            /** @description Base DNS domain for the cluster */
            baseDomain: string;
            /** @description OpenShift cluster name */
            clusterName: string;
            /** @description Additional NTP server addresses */
            defaultNtpServers?: string[] | null;
            /** @description Enable TPM v2 disk encryption */
            diskEncryption?: boolean;
            /** @description Virtual IP for ingress wildcard */
            ingressVIP: string;
            /** @description Network CIDR for cluster nodes */
            machineNetwork: string;
            /**
             * Format: int64
             * @description Maximum pods per node (default: 500)
             */
            masterMaxPods?: number;
            /** @description OpenShift pull secret object */
            pullSecret: unknown;
            /** @description IP of first control-plane node */
            rendezvousIP: string;
            /** @description Path to SSH public key file */
            sshPubPath: string;
        };
        Defaults: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Defaults.json
             */
            readonly $schema?: string;
            disconnected: boolean;
            diskEncryption: boolean;
            lvmsDefaults?: components["schemas"]["LVMSConfig"];
            /** Format: int64 */
            masterMaxPods: number;
            ocMirrorLogLevel: string;
            odfDefaults?: components["schemas"]["ODFConfig"];
            storagePlugin: string;
            vastDefaults?: components["schemas"]["VASTConfig"];
        };
        EnclaveConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/EnclaveConfig.json
             */
            readonly $schema?: string;
            /** @description TLS certificates (certificates.yaml) */
            certificates: components["schemas"]["CertificatesConfig"];
            /** @description Cloud infrastructure / discovery hosts (cloud_infra.yaml) */
            cloudInfra: components["schemas"]["CloudInfraConfig"];
            /** @description Primary cluster configuration (global.yaml) */
            global: components["schemas"]["GlobalConfig"];
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GetTaskEventsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetTaskEventsOutputBody.json
             */
            readonly $schema?: string;
            /** @description Ansible Runner job events */
            events: unknown[] | null;
        };
        GlobalConfig: {
            /** @description Control plane nodes (exactly 3) */
            agent_hosts: components["schemas"]["HostEntry"][] | null;
            /** @description Virtual IP for Kubernetes API server */
            apiVIP: string;
            /** @description Base DNS domain for the cluster */
            baseDomain: string;
            /** @description OpenShift cluster name */
            clusterName: string;
            /** @description DNS server IP for cluster nodes */
            defaultDNS: string;
            /** @description Default gateway IP for cluster nodes */
            defaultGateway: string;
            /** @description Additional NTP server addresses */
            defaultNtpServers?: string[] | null;
            /**
             * Format: int64
             * @description Subnet prefix length
             */
            defaultPrefix: number;
            /** @description Air-gapped deployment mode (default: true) */
            disconnected?: boolean;
            /** @description Enable TPM v2 disk encryption */
            diskEncryption?: boolean;
            /** @description Plugins to deploy */
            enabled_plugins?: string[] | null;
            /** @description Virtual IP for ingress wildcard */
            ingressVIP: string;
            /** @description LVMS device selector configuration */
            lvmsConfig?: components["schemas"]["LVMSStorageConfig"];
            /** @description DNS hostname for landing zone BMC interface */
            lzBmcHostname?: string;
            /** @description Landing zone BMC IP for boot ISO serving */
            lzBmcIP: string;
            /** @description Network CIDR for cluster nodes */
            machineNetwork: string;
            /**
             * Format: int64
             * @description Maximum pods per node (default: 500)
             */
            masterMaxPods?: number;
            /**
             * @description oc-mirror log level
             * @enum {string}
             */
            ocMirrorLogLevel?: "trace" | "debug" | "info" | "error";
            /** @description ODF deployment configuration */
            odfDefaults?: components["schemas"]["ODFConfig"];
            /** @description ODF external Ceph cluster config JSON (required when storage_plugin is odf) */
            odfExternalConfig?: string;
            /**
             * @description Fully-qualified Ansible role name of the DNS driver
             * @enum {string}
             */
            osacDnsClass?: "dns.route53.dns";
            /** @description DNS zone to operate in (defaults to EXTERNAL_ACCESS_BASE_DOMAIN) */
            osacDnsZone?: string;
            /** @description OpenShift pull secret object */
            pullSecret: unknown;
            /**
             * @description Quay image storage backend
             * @enum {string}
             */
            quayBackend: "RadosGWStorage" | "LocalStorage";
            /** @description RadosGW/S3 backend config (required when quayBackend is RadosGWStorage) */
            quayBackendRGWConfiguration?: components["schemas"]["QuayBackendRGWConfiguration"];
            /** @description Admin password for Quay registry */
            quayPassword: string;
            /** @description Admin username for Quay registry */
            quayUser: string;
            /** @description IP of first control-plane node */
            rendezvousIP: string;
            /** @description Path to SSH public key file */
            sshPubPath: string;
            /**
             * @description Storage plugin
             * @enum {string}
             */
            storage_plugin: "lvms" | "odf" | "vast-csi";
            /** @description VAST management API password */
            vastAdminPassword?: string;
            /** @description VAST management API username */
            vastAdminUsername?: string;
            /** @description VAST CSI deployment defaults */
            vastDefaults?: components["schemas"]["VASTConfig"];
            /** @description VAST management endpoint URL (required when storage_plugin is vast-csi) */
            vastEndpoint?: string;
            /** @description VIP pool configuration for CSI traffic (required when storage_plugin is vast-csi) */
            vastVipPool?: components["schemas"]["VASTVipPool"];
            /** @description Absolute path to root working directory */
            workingDir: string;
        };
        HostEntry: {
            /** @description Redfish system ID path component (default: 1) */
            bmcSystemId?: string;
            /** @description Node IPv4 address within machineNetwork */
            ipAddress: string;
            /** @description MAC address (xx:xx:xx:xx:xx:xx) */
            macAddress: string;
            /** @description Interface mapping for complex topologies */
            mapInterfaces?: unknown;
            /** @description Node name label */
            name: string;
            /** @description NMState network configuration for multi-NIC/VLAN */
            networkConfig?: unknown;
            /** @description Redfish/IPMI management IP */
            redfish: string;
            /** @description Redfish password */
            redfishPassword: string;
            /** @description Redfish username */
            redfishUser: string;
            /** @description Root disk path for OS installation */
            rootDisk: string;
        };
        LVMSConfig: {
            /** @description Set as default StorageClass */
            defaultStorageClass: boolean;
            /** @description LVM volume group device class name */
            deviceClassName: string;
            /** @description Thin pool settings */
            thinPoolConfig: components["schemas"]["LVMSThinPoolConfig"];
        };
        LVMSDeviceSelector: {
            /** @description Disk device paths for LVM volume group */
            optionalPaths?: string[] | null;
        };
        LVMSStorageConfig: {
            /** @description LVMS device selector */
            deviceSelector: components["schemas"]["LVMSDeviceSelector"];
        };
        LVMSThinPoolConfig: {
            /** @description Thin pool name */
            name: string;
            /**
             * Format: int64
             * @description Thin pool overprovisioning ratio
             */
            overprovisionRatio: number;
            /**
             * Format: int64
             * @description Pool size as percentage of volume group
             */
            sizePercent: number;
        };
        LandingZoneConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LandingZoneConfig.json
             */
            readonly $schema?: string;
            /** @description Air-gapped deployment mode (default: true) */
            disconnected?: boolean;
            /** @description DNS hostname for landing zone BMC interface */
            lzBmcHostname?: string;
            /** @description Landing zone BMC IP for boot ISO serving */
            lzBmcIP: string;
            /** @description Absolute path to root working directory */
            workingDir: string;
        };
        ListTasksOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListTasksOutputBody.json
             */
            readonly $schema?: string;
            /** @description All known task runs */
            runs: components["schemas"]["TaskRun"][] | null;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            /** @description Password */
            password: string;
            /** @description Username (always 'admin') */
            username: string;
        };
        LoginOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LoginOutputBody.json
             */
            readonly $schema?: string;
            /** @description True if the initial password has not been changed yet */
            mustChangePassword: boolean;
            /** @description Bearer token for API access */
            token: string;
        };
        NetworkConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NetworkConfig.json
             */
            readonly $schema?: string;
            /** @description DNS server IP for cluster nodes */
            defaultDNS: string;
            /** @description Default gateway IP for cluster nodes */
            defaultGateway: string;
            /**
             * Format: int64
             * @description Subnet prefix length
             */
            defaultPrefix: number;
        };
        ODFConfig: {
            /** @description Set as default StorageClass */
            defaultStorageClass: boolean;
        };
        Plugin: {
            /** @description Human-readable description */
            description: string;
            /** @description Plugin identifier */
            name: string;
            /**
             * @description Plugin type
             * @enum {string}
             */
            type: "foundation" | "addon";
        };
        PluginValidateInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PluginValidateInputBody.json
             */
            readonly $schema?: string;
            /** @description Plugin names to validate as a combination */
            plugins: string[] | null;
        };
        PluginValidateOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PluginValidateOutputBody.json
             */
            readonly $schema?: string;
            /** @description Validation errors, if any */
            errors?: components["schemas"]["ValidationError"][] | null;
            /** @description Whether the combination is valid */
            valid: boolean;
        };
        PluginsConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PluginsConfig.json
             */
            readonly $schema?: string;
            /** @description Plugins to deploy */
            enabled_plugins?: string[] | null;
            /** @description LVMS deployment configuration */
            lvmsDefaults?: components["schemas"]["LVMSConfig"];
            /** @description ODF deployment configuration */
            odfDefaults?: components["schemas"]["ODFConfig"];
            /**
             * @description Fully-qualified Ansible role name of the DNS driver
             * @enum {string}
             */
            osacDnsClass?: "dns.route53.dns";
            /** @description DNS zone to operate in (defaults to EXTERNAL_ACCESS_BASE_DOMAIN) */
            osacDnsZone?: string;
            /** @description VAST CSI deployment defaults */
            vastDefaults?: components["schemas"]["VASTConfig"];
        };
        PluginsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PluginsOutputBody.json
             */
            readonly $schema?: string;
            /** @description Available plugins */
            plugins: components["schemas"]["Plugin"][] | null;
        };
        PreviewConfigOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PreviewConfigOutputBody.json
             */
            readonly $schema?: string;
            /** @description Rendered certificates.yaml content */
            certificatesYaml: string;
            /** @description Rendered cloud_infra.yaml content */
            cloudInfraYaml: string;
            /** @description Rendered global.yaml content */
            globalYaml: string;
        };
        QuayBackendRGWConfiguration: {
            /** @description S3/RGW access key ID */
            access_key: string;
            /** @description S3 bucket name for Quay image storage */
            bucket_name: string;
            /** @description RadosGW/S3 endpoint hostname */
            hostname: string;
            /** @description Use HTTPS for backend storage (default: true) */
            is_secure?: boolean;
            /**
             * Format: int64
             * @description Maximum multipart upload chunk size in MB
             */
            maximum_chunk_size_mb?: number;
            /**
             * Format: int64
             * @description Minimum multipart upload chunk size in MB
             */
            minimum_chunk_size_mb?: number;
            /**
             * Format: int64
             * @description Backend storage endpoint port (default: 443)
             */
            port?: number;
            /** @description S3/RGW secret access key */
            secret_key: string;
            /** @description Enable server-side assembly for multipart uploads */
            server_side_assembly?: boolean;
            /** @description Object storage path prefix (must start with /) */
            storage_path?: string;
        };
        QuayConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/QuayConfig.json
             */
            readonly $schema?: string;
            /**
             * @description oc-mirror log level
             * @enum {string}
             */
            ocMirrorLogLevel?: "trace" | "debug" | "info" | "error";
            /**
             * @description Quay image storage backend
             * @enum {string}
             */
            quayBackend: "RadosGWStorage" | "LocalStorage";
            /** @description RadosGW/S3 backend config (required when quayBackend is RadosGWStorage) */
            quayBackendRGWConfiguration?: components["schemas"]["QuayBackendRGWConfiguration"];
            /** @description Admin password for Quay registry */
            quayPassword: string;
            /** @description Admin username for Quay registry */
            quayUser: string;
        };
        StorageConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StorageConfig.json
             */
            readonly $schema?: string;
            /** @description LVMS device selector configuration */
            lvmsConfig?: components["schemas"]["LVMSStorageConfig"];
            /** @description ODF external Ceph cluster config JSON (required when storage_plugin is odf) */
            odfExternalConfig?: string;
            /**
             * @description Storage plugin
             * @enum {string}
             */
            storage_plugin: "lvms" | "odf" | "vast-csi";
            /** @description VAST management API password */
            vastAdminPassword?: string;
            /** @description VAST management API username */
            vastAdminUsername?: string;
            /** @description VAST management endpoint URL (required when storage_plugin is vast-csi) */
            vastEndpoint?: string;
            /** @description VIP pool configuration for CSI traffic (required when storage_plugin is vast-csi) */
            vastVipPool?: components["schemas"]["VASTVipPool"];
        };
        TaskRun: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TaskRun.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description When the run completed
             */
            endedAt?: string;
            /** @description Error message if failed */
            error?: string;
            /**
             * Format: int64
             * @description Process exit code
             */
            exitCode?: number;
            /** @description Extra variables passed to ansible-runner */
            extraVars?: {
                [key: string]: string;
            };
            /** @description Unique run identifier */
            id: string;
            /**
             * Format: int64
             * @description OS process ID of ansible-runner
             */
            pid?: number;
            /** @description Playbook path relative to enclave directory */
            playbook: string;
            /**
             * Format: date-time
             * @description When ansible-runner started
             */
            startedAt: string;
            /**
             * @description Current execution status
             * @enum {string}
             */
            status: "running" | "successful" | "failed" | "canceled";
            /**
             * @description Type of task
             * @enum {string}
             */
            type: "deploy" | "deploy-phase" | "deploy-plugin" | "validate";
        };
        VASTConfig: {
            /** @description Tenant name for infrastructure resources */
            infraTenant?: string;
            /** @description PVC size for Quay storage tier (e.g. 1000Gi) */
            quayPvcSize?: string;
            /** @description Root path on VAST cluster */
            storagePath?: string;
            /** @description Storage tiers to create on the VAST cluster */
            tiers?: components["schemas"]["VASTTier"][] | null;
            /**
             * Format: int64
             * @description VAST view policy ID
             */
            viewPolicyId?: number;
        };
        VASTIPRange: {
            /** @description End IP address of the range */
            end: string;
            /** @description Start IP address of the range */
            start: string;
        };
        VASTTier: {
            /** @description Storage tier name (becomes StorageClass suffix) */
            name: string;
            /**
             * @description Storage protocol
             * @enum {string}
             */
            protocol: "nfs" | "block";
        };
        VASTVipPool: {
            /** @description IP address ranges for VIP allocation */
            ip_ranges: components["schemas"]["VASTIPRange"][] | null;
            /**
             * Format: int64
             * @description Subnet prefix length
             */
            subnet_cidr: number;
        };
        ValidateConfigOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ValidateConfigOutputBody.json
             */
            readonly $schema?: string;
            /** @description Validation errors, if any */
            errors?: components["schemas"]["ValidationError"][] | null;
            /** @description Whether the config passes all validation checks */
            valid: boolean;
        };
        ValidationError: {
            /** @description JSON path to the invalid field */
            field: string;
            /** @description Human-readable error description */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnclaveConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnclaveConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config-certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificatesConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config-certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificatesConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config-cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config-cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config-hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudInfraConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config-hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudInfraConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config-lz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandingZoneConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config-lz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LandingZoneConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config-network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config-network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config-plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginsConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config-plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PluginsConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "preview-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnclaveConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewConfigOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config-quay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuayConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config-quay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuayConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-config-storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "write-config-storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageConfig"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "validate-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnclaveConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateConfigOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Defaults"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "validate-plugin-combination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PluginValidateInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginValidateOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTasksOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "start-deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "start-deploy-phase": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment phase number (1-7) */
                phase: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "start-deploy-plugin": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "start-validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-task": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRun"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-task": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-task-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTaskEventsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-task-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
