// Code generated by schemagen. DO NOT EDIT.
package schema

type OsacConfig struct {
	OsacAapLicenseFile        string          `yaml:"osacAapLicenseFile" json:"osacAapLicenseFile" doc:"Path to AAP license manifest.zip file on the Landing Zone"`
	OsacBYODatabase           *bool           `yaml:"osacBYODatabase,omitempty" json:"osacBYODatabase,omitempty" doc:"Set to true to use an external database instead of the built-in dev postgres"`
	OsacBcmBmhNamespace       *string         `yaml:"osacBcmBmhNamespace,omitempty" json:"osacBcmBmhNamespace,omitempty" doc:"Namespace where BareMetalHost CRs are created for Metal3 power management" minLength:"1"`
	OsacBcmCaCert             *string         `yaml:"osacBcmCaCert,omitempty" json:"osacBcmCaCert,omitempty" doc:"PEM-encoded CA certificate for verifying BCM server cert (optional)" minLength:"1"`
	OsacBcmCert               *string         `yaml:"osacBcmCert,omitempty" json:"osacBcmCert,omitempty" doc:"PEM-encoded client certificate for BCM mTLS authentication" minLength:"1"`
	OsacBcmEnabled            *bool           `yaml:"osacBcmEnabled,omitempty" json:"osacBcmEnabled,omitempty" doc:"Enable BCM inventory backend for bare metal fulfillment"`
	OsacBcmHostClass          *string         `yaml:"osacBcmHostClass,omitempty" json:"osacBcmHostClass,omitempty" doc:"Host class identifier for BCM inventory (default: bcm)" minLength:"1"`
	OsacBcmInsecureSkipVerify *bool           `yaml:"osacBcmInsecureSkipVerify,omitempty" json:"osacBcmInsecureSkipVerify,omitempty" doc:"Skip TLS verification of BCM server certificate (test environments only)"`
	OsacBcmKey                *string         `yaml:"osacBcmKey,omitempty" json:"osacBcmKey,omitempty" doc:"PEM-encoded client private key for BCM mTLS authentication" minLength:"1"`
	OsacBcmUrl                *string         `yaml:"osacBcmUrl,omitempty" json:"osacBcmUrl,omitempty" doc:"BCM head node API endpoint (e.g. https://bcm-head:8081)" minLength:"1" pattern:"^https://"`
	OsacChartVersion          *string         `yaml:"osacChartVersion,omitempty" json:"osacChartVersion,omitempty" doc:"OSAC Helm chart version to deploy (overrides default from defaults.yaml)" minLength:"1"`
	OsacDatabaseUrl           *string         `yaml:"osacDatabaseUrl,omitempty" json:"osacDatabaseUrl,omitempty" doc:"Connection URL for external database. When provided with osacBYODatabase=true, post-operators.yaml creates the fulfillment-db secret from this value. If omitted, the user must pre-create the fulfillment-db secret manually."`
	OsacDnsClass              *string         `yaml:"osacDnsClass,omitempty" json:"osacDnsClass,omitempty" doc:"Fully-qualified Ansible role name of the DNS driver" enum:"dns.route53.dns"`
	OsacDnsZone               *string         `yaml:"osacDnsZone,omitempty" json:"osacDnsZone,omitempty" doc:"DNS zone to operate in (defaults to EXTERNAL_ACCESS_BASE_DOMAIN)"`
	OsacMetal3Enabled         *bool           `yaml:"osacMetal3Enabled,omitempty" json:"osacMetal3Enabled,omitempty" doc:"Enable Metal3 inventory backend for bare metal fulfillment"`
	OsacMetal3HostClass       *string         `yaml:"osacMetal3HostClass,omitempty" json:"osacMetal3HostClass,omitempty" doc:"Host class identifier for Metal3 inventory (default: metal3)" minLength:"1"`
	OsacMetal3Namespace       *string         `yaml:"osacMetal3Namespace,omitempty" json:"osacMetal3Namespace,omitempty" doc:"Namespace where BareMetalHost CRs are located" minLength:"1"`
	OsacNetworking            *map[string]any `yaml:"osacNetworking,omitempty" json:"osacNetworking,omitempty" doc:"High-level networking profile passed through to Helm global.networking. Mirrors osac-installer values.schema.json $defs/globalNetworking."`
	OsacProfilesList          *[]string       `yaml:"osacProfilesList,omitempty" json:"osacProfilesList,omitempty" doc:"List of enabled service profiles: vmaas, caas, bmaas" minItems:"1"`
	OsacTestUsers             *bool           `yaml:"osacTestUsers,omitempty" json:"osacTestUsers,omitempty" doc:"Create test users in the Keycloak osac realm for initial UI/CLI access"`
	Images                    *map[string]any `yaml:"osac_images,omitempty" json:"osacImages,omitempty" doc:"Optional container image overrides. When unset, the Helm chart's built-in image references are used."`
}
